### PR TITLE
Fix MSRV violation in `parse.rs` test, check `--all-targets` in MSRV CI

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

N/A — follow-up to a report by @progval in https://github.com/apache/arrow-rs-object-store/pull/812#issuecomment-5061268463

# Rationale for this change

Some things still fail to compile on main with 1.85

```
error[E0599]: no function or associated item named `from_utf8` found for type `str` in the current scope
   --> src/parse.rs:477:25
    |
477 |         let body = str::from_utf8(&body).unwrap();
    |                         ^^^^^^^^^ function or associated item not found in `str`
```

CI did not catch this because the MSRV job runs doesn't check all targeets

# What changes are included in this PR?

1. Update MSRV check to include all targets
1. Fix MSRV 1.85 issues

# Are these changes tested?

Yes by CI
# Are there any user-facing changes?

No, test and CI changes only.

### CODE REVIEW

**Review by kylebarron — APPROVED** [review]
Thanks!
